services:
  postgres:
    image: postgres:16
    container_name: securepass_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ~/Desktop/docker-data/postgres:/var/lib/postgresql/data
    networks:
      - securepass_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: securepass_pgadmin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ~/Desktop/docker-data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - securepass_net

  springboot-app:
    build:
      context:  ./securepass-backend
    container_name: securepass_backend
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - securepass_net

  frontend:
    build:
      context: ./securepass-frontend
      dockerfile: Dockerfile
    container_name: securepass_frontend
    ports:
      - "4200:80"
    networks:
      - securepass_net

networks:
  securepass_net:

